import 'package:woolet/core/constants/app_enums.dart';
import 'package:woolet/features/domain/entities/category_entity.dart';

abstract final class DefaultCategories {
  static List<CategoryEntity> create({DateTime? createdAt}) {
    final creationDate = (createdAt ?? DateTime.now()).toUtc();

    return List.unmodifiable([
      _category(
        uuid: '59da9e01-f829-46e9-b05e-d75764910edd',
        name: 'Salary',
        sortOrder: 0,
        iconCode: 'briefcase',
        colorValue: 0xFF16A34A,
        type: CategoryType.income,
        createdAt: creationDate,
      ),
      _category(
        uuid: '583f2a8c-1861-4a6a-add9-229855479ac6',
        name: 'Freelance',
        sortOrder: 1,
        iconCode: 'banknote',
        colorValue: 0xFF0D9488,
        type: CategoryType.income,
        createdAt: creationDate,
      ),
      _category(
        uuid: '6ec2471d-de51-4c8a-96c2-ce907936b336',
        name: 'Investments',
        sortOrder: 2,
        iconCode: 'trending_up',
        colorValue: 0xFF2563EB,
        type: CategoryType.income,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'df0af800-d22f-4030-a078-f6c2f4918cc5',
        name: 'Gifts',
        sortOrder: 3,
        iconCode: 'gift',
        colorValue: 0xFFDB2777,
        type: CategoryType.income,
        createdAt: creationDate,
      ),
      _category(
        uuid: '59164b18-4cb2-4025-ad41-e8da77841e8b',
        name: 'Interest',
        sortOrder: 4,
        iconCode: 'landmark',
        colorValue: 0xFF0891B2,
        type: CategoryType.income,
        createdAt: creationDate,
      ),
      _category(
        uuid: '84b532c7-1467-42c7-9ff9-a0ed00299f09',
        name: 'Other',
        sortOrder: 5,
        iconCode: 'circle_dollar_sign',
        colorValue: 0xFF059669,
        type: CategoryType.income,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'ba38fd0b-0041-4bb5-93a5-be2704cd3f3b',
        name: 'Groceries',
        sortOrder: 0,
        iconCode: 'groceries',
        colorValue: 0xFFEA580C,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'a7255a5f-fdaf-409d-a3fa-0a45bd3b92b5',
        name: 'Cafe',
        sortOrder: 1,
        iconCode: 'cafe',
        colorValue: 0xFFD97706,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: '2b258089-75fa-4a8f-86bb-75b00062bf95',
        name: 'Entertainment',
        sortOrder: 2,
        iconCode: 'entertainment',
        colorValue: 0xFF7C3AED,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: '48510a79-a41e-4ea5-98f9-67cab687ea1d',
        name: 'Fuel',
        sortOrder: 3,
        iconCode: 'fuel',
        colorValue: 0xFFDC2626,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'a2a7558d-eb4f-40cc-92d3-917ba1282106',
        name: 'Shopping',
        sortOrder: 4,
        iconCode: 'shopping',
        colorValue: 0xFFE11D48,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'ee000bf5-75c1-4bb8-83e5-540d2e6d09a4',
        name: 'Taxi',
        sortOrder: 5,
        iconCode: 'taxi',
        colorValue: 0xFFCA8A04,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: '1edc421b-c3a7-4f1d-a1e5-05f405b32526',
        name: 'Home',
        sortOrder: 6,
        iconCode: 'home',
        colorValue: 0xFF4F46E5,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'eb4796c6-1bdb-4923-a709-9ad9888b727c',
        name: 'Car',
        sortOrder: 7,
        iconCode: 'car',
        colorValue: 0xFF475569,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: '6fd16f25-c2d5-464d-814d-67f7eaf817d0',
        name: 'Pharmacy',
        sortOrder: 8,
        iconCode: 'pharmacy',
        colorValue: 0xFFC026D3,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
      _category(
        uuid: 'dc1d5208-7228-4ea9-a3dc-218bc601c859',
        name: 'Other',
        sortOrder: 9,
        iconCode: 'wallet',
        colorValue: 0xFF64748B,
        type: CategoryType.expense,
        createdAt: creationDate,
      ),
    ]);
  }

  static CategoryEntity _category({
    required String uuid,
    required String name,
    required int sortOrder,
    required String iconCode,
    required int colorValue,
    required CategoryType type,
    required DateTime createdAt,
  }) {
    return CategoryEntity(
      uuid: uuid,
      name: name,
      sortOrder: sortOrder,
      iconCode: iconCode,
      colorValue: colorValue,
      createdAt: createdAt,
      type: type,
    );
  }
}
